# Generated by Django 5.2.7 on 2025-11-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_orders', models.IntegerField()),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('top_selling_product', models.CharField(max_length=100)),
                ('low_stock_count', models.IntegerField()),
            ],
        ),
    ]
